apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akv-litellm
  namespace: litellm
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: ${ARC_KEYVAULT_NAME}
    cloudName: "${ARC_CSI_CLOUD_NAME}"
    tenantId: ${ARC_TENANT_ID}
    objects: |
      array:
        - |
          objectName: litellm-master-key
          objectType: secret
        - |
          objectName: openai-api-key
          objectType: secret
        - |
          objectName: pgvector-password
          objectType: secret
  secretObjects:
    - secretName: litellm-secrets
      type: Opaque
      data:
        - objectName: litellm-master-key
          key: LITELLM_MASTER_KEY
        - objectName: openai-api-key
          key: OPENAI_API_KEY
        - objectName: pgvector-password
          key: PGVECTOR_PASSWORD
