apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akv-code-server
  namespace: code-server
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: ${ARC_KEYVAULT_NAME}
    cloudName: "${ARC_CSI_CLOUD_NAME}"
    tenantId: ${ARC_TENANT_ID}
    objects: |
      array:
        - |
          objectName: code-server-password
          objectType: secret
  secretObjects:
    - secretName: code-server-secrets
      type: Opaque
      data:
        - objectName: code-server-password
          key: PASSWORD
