apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akv-pgvector
  namespace: pgvector
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: arc-onboard-kv
    cloudName: AzureUSGovernmentCloud
    tenantId: 80c5c29b-f6c2-457b-af54-603a8d840878
    objects: |
      array:
        - |
          objectName: pgvector-password
          objectType: secret
  secretObjects:
    - secretName: pgvector-secrets
      type: Opaque
      data:
        - objectName: pgvector-password
          key: POSTGRES_PASSWORD
