apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akv-dify
  namespace: dify
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: arc-onboard-kv
    tenantId: 1af9ebd3-3f5b-407b-824c-973cc3334dca
    objects: |
      array:
        - |
          objectName: pgvector-password
          objectType: secret
  secretObjects:
    - secretName: dify-secrets
      type: Opaque
      data:
        - objectName: pgvector-password
          key: DB_PASSWORD
