apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: akv-dify
  namespace: dify
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: ${ARC_KEYVAULT_NAME}
    cloudName: "${ARC_CSI_CLOUD_NAME}"
    tenantId: ${ARC_TENANT_ID}
    objects: |
      array:
        - |
          objectName: pgvector-password
          objectType: secret
  secretObjects:
    - secretName: dify-secrets
      type: Opaque
      data:
        - objectName: pgvector-password
          key: DB_PASSWORD
