apiVersion: v1
kind: Service
metadata:
  name: dify-api
  namespace: dify
spec:
  selector:
    app: dify-api
  ports:
    - port: 5001
      targetPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: dify-web
  namespace: dify
spec:
  selector:
    app: dify-web
  ports:
    - port: 3000
      targetPort: 3000
